/* KFC Smart Scheduler — fresh implementation, no legacy code */
(()=>{'use strict';
const cfg=window.KFC_CONFIG, pages=['班表總覽','階梯排班','TC 需求預測','員工管理','員工指休','國定假日／特殊日期對照','人員工時統計','員工休假合規檢查','系統設定'];
const $=id=>document.getElementById(id), esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={page:0,token:null,refresh:null,profile:null,centers:[],restaurants:[],employees:[],supports:[],regular:[],exceptions:[],dms:[],rosters:[],weekStart:weekMonday(new Date()),center:'',group:'',day:localDate(new Date()),month:localDate(new Date()).slice(0,7),tplh:2,forecastPct:0,forecastDate:addDays(localDate(new Date()),7),forecastResult:null,forecastBusy:false,slotType:'delivery',editing:false,selectedEmployee:null,localDraft:{},errors:[],sync:{},monthRosters:[],monthLoaded:'',undoStack:[],complianceRange:'week',overviewDay:'',operatingStart:localStorage.getItem('kfc_operating_start')||'08:00',operatingEnd:localStorage.getItem('kfc_operating_end')||'01:00'};
function localDate(d){const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)}function addDays(date,n){const d=new Date(date+'T12:00:00');d.setDate(d.getDate()+n);return localDate(d)}function weekMonday(d){const dt=new Date(d);dt.setDate(dt.getDate()-(dt.getDay()+6)%7);return localDate(dt)}function num(n,d=0){return Number(n||0).toLocaleString('zh-TW',{maximumFractionDigits:d,minimumFractionDigits:d})}function dateInWeek(date){return date>=state.weekStart&&date<=addDays(state.weekStart,6)}function minuteOf(t){const [h,m]=String(t).split(':').map(Number);return h*60+m}function operatingTimes(){const start=minuteOf(state.operatingStart),end=minuteOf(state.operatingEnd),length=(end<=start?end+1440:end)-start;return Array.from({length:Math.floor(length/30)},(_,i)=>{const n=(start+i*30)%1440;return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`})}function timeIndex(t){return slots.indexOf(String(t).slice(0,5))}function slotTime(i){return slots[i]||''}let slots=operatingTimes();function refreshOperatingTimes(){slots=operatingTimes()}
function key(d,g){return `${d}|${g}`}
function notify(message,bad=false){$('notice').textContent=message||'';if(bad)console.warn(message)}
function authHeaders(extra={}){return {'apikey':cfg.anonKey,'Authorization':`Bearer ${state.token||cfg.anonKey}`,...extra}}
async function request(path,{method='GET',body,headers={}}={}){const response=await fetch(`${cfg.url}${path}`,{method,headers:authHeaders({...headers,...(body?{'Content-Type':'application/json'}:{})}),body:body?JSON.stringify(body):undefined});const raw=await response.text();let data;try{data=raw?JSON.parse(raw):null}catch{data=raw}if(!response.ok){const msg=data?.message||data?.error_description||data?.msg||`HTTP ${response.status}`;throw new Error(`${msg} (${response.status})`)}return data}
const rest=(table,query='',options={})=>request(`/rest/v1/${table}${query?`?${query}`:''}`,options);
async function login(email,password){const a=await request('/auth/v1/token?grant_type=password',{method:'POST',body:{email,password}});state.token=a.access_token;state.refresh=a.refresh_token;sessionStorage.setItem('kfc_session',JSON.stringify({token:state.token,refresh:state.refresh}));await bootstrap()}
async function refreshToken(){if(!state.refresh)throw new Error('請重新登入');const a=await request('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:state.refresh}});state.token=a.access_token;state.refresh=a.refresh_token;sessionStorage.setItem('kfc_session',JSON.stringify({token:state.token,refresh:state.refresh}))}
async function read(table,query=''){try{const rows=await rest(table,query);state.sync[table]='成功';return rows||[]}catch(e){state.sync[table]=`失敗：${e.message}`;state.errors.push(`${table}: ${e.message}`);throw new Error(`${table} 讀取失敗：${e.message}`)}}
async function bootstrap(){state.errors=[];try{const user=await request('/auth/v1/user');const ps=await read('profiles',`select=*&user_id=eq.${encodeURIComponent(user.id)}&limit=1`);state.profile=ps[0];if(!state.profile?.active)throw new Error('此帳號沒有啟用的管理權限');state.centers=await read('centers','select=*&active=eq.true&order=name');state.center=state.profile.role==='op_admin'||state.profile.role==='admin'?'':state.profile.center_id||'';await loadCore();$('loginOverlay').hidden=true;$('logout').hidden=false;$('who').textContent=state.profile.display_name||'';$('status').textContent='已登入 Supabase';$('status').className='pill ok';render()}catch(e){$('loginOverlay').hidden=false;$('loginError').textContent=e.message;$('status').textContent='尚未連線';$('status').className='pill bad'}}
async function loadCore(){state.errors=[];const [restaurants,employees]=await Promise.all([read('restaurants','select=*&active=eq.true&order=restaurant_name'),read('scheduler_employees','select=*&order=employee_name')]);state.restaurants=restaurants;state.employees=employees;const [supports,regular,exceptions]=await Promise.all([read('scheduler_employee_support_groups','select=*'),read('scheduler_regular_availability','select=*'),read('scheduler_weekly_exceptions',`select=*&work_date=gte.${state.weekStart}&work_date=lte.${addDays(state.weekStart,6)}`)]);state.supports=supports;state.regular=regular;state.exceptions=exceptions;await loadWeek()}
async function loadWeek(){const end=addDays(state.weekStart,6);const [dms,rosters]=await Promise.all([read('dms_30m',`select=center_id,restaurant_id,business_date,bucket_time,own_tc,tc,third_party_tc&business_date=gte.${state.weekStart}&business_date=lte.${end}&limit=100000`),read('scheduler_daily_rosters',`select=*&work_date=gte.${state.weekStart}&work_date=lte.${end}&limit=10000`)]);state.dms=dms;state.rosters=rosters;state.localDraft={};if(!dateInWeek(state.day))state.day=state.weekStart}
function groups(){const g=new Set(state.restaurants.filter(r=>!state.center||r.center_id===state.center).map(r=>r.region_code).filter(Boolean));state.employees.filter(e=>!state.center||e.center_id===state.center).forEach(e=>e.group_code&&g.add(e.group_code));return [...g].sort()}
function filteredRestaurants(){return state.restaurants.filter(r=>(!state.center||r.center_id===state.center)&&(!state.group||r.region_code===state.group))}
function filteredEmployees(){return state.employees.filter(e=>(!state.center||e.center_id===state.center)&&(!state.group||e.group_code===state.group||state.supports.some(s=>s.employee_id===e.id&&s.group_code===state.group)))}
function filterDms(){const ids=new Set(filteredRestaurants().map(r=>String(r.id)));return state.dms.filter(x=>(!state.center||x.center_id===state.center)&&ids.has(String(x.restaurant_id)))}
function totalTc(data=filterDms()){return data.reduce((s,x)=>s+Number(x.own_tc||0),0)}
function rowsOf(rec){if(!rec)return [];if(Array.isArray(rec.rows))return rec.rows;if(Array.isArray(rec.rows?.rows))return rec.rows.rows;return []}
function rawWorkType(x){return String(x||'').toLowerCase()}
function getRoster(d,g){const id=key(d,g);if(state.localDraft[id])return state.localDraft[id];const found=state.rosters.find(r=>r.work_date===d&&r.group_code===g&&(!state.center||r.center_id===state.center));return rowsOf(found)}
function normalizeRow(r){return {employee_id:r.employee_id||r.id||null,employee_name:r.employee_name||r.name||'',slots:r.slots||r.cells||r.schedule||{}}}
function slotValue(row,i){const s=row.slots;if(Array.isArray(s))return rawWorkType(s[i]?.type||s[i]||'');if(s&&typeof s==='object')return rawWorkType(s[slotTime(i)]?.type||s[slotTime(i)]||s[i]?.type||s[i]||'');return ''}
function rowHours(row){return slots.reduce((n,_,i)=>n+(slotValue(row,i)&&slotValue(row,i)!=='break'?0.5:0),0)}
function uniqueHours(rows){const seen=new Set();let n=0;for(const r of rows)for(let i=0;i<slots.length;i++){const v=slotValue(r,i);if(!v||v==='break')continue;const k=`${r.employee_id||r.employee_name}|${r.work_date}|${slotTime(i)}`;if(!seen.has(k)){seen.add(k);n+=.5}}return n}
async function fetchAll(table,query='',pageSize=1000){const result=[];for(let offset=0;offset<200000;offset+=pageSize){const join=query?query+'&':'';const page=await rest(table,join+`limit=${pageSize}&offset=${offset}`);if(!Array.isArray(page))throw Error('API 回傳格式不正確');result.push(...page);if(page.length<pageSize)return result}throw Error('資料超過 200,000 筆，已停止以避免漏算')}
async function loadMonth(){const start=state.month+'-01',end=localDate(new Date(Number(state.month.slice(0,4)),Number(state.month.slice(5,7)),0,12));state.monthLoaded='';try{state.monthRosters=await fetchAll('scheduler_daily_rosters',`select=*&work_date=gte.${start}&work_date=lte.${end}`);state.monthLoaded=state.month}catch(e){state.monthRosters=[];notify('整月班表讀取失敗：'+e.message,true)}}
function monthRows(){if(state.monthLoaded!==state.month)return [];return state.monthRosters.filter(r=>(!state.center||r.center_id===state.center)&&(!state.group||r.group_code===state.group)).flatMap(r=>rowsOf(r).map(x=>({...normalizeRow(x),work_date:r.work_date,group_code:r.group_code})))}
function rosterRows(d){return state.rosters.filter(r=>r.work_date===d&&(!state.center||r.center_id===state.center)&&(!state.group||r.group_code===state.group)).flatMap(r=>getRoster(d,r.group_code).map(x=>({...normalizeRow(x),group_code:r.group_code})))}
function allRosterRows(){const keys=new Set(state.rosters.filter(r=>(!state.center||r.center_id===state.center)&&(!state.group||r.group_code===state.group)).map(r=>key(r.work_date,r.group_code)));Object.keys(state.localDraft).forEach(k=>keys.add(k));return [...keys].flatMap(k=>{const [d,g]=k.split('|');return getRoster(d,g).map(r=>({...normalizeRow(r),work_date:d,group_code:g}))})}
function kpi(label,value,sub='',red=false){return `<div class="kpi ${red?'red':''}"><div class="label">${esc(label)}</div><strong>${esc(value)}</strong><small>${esc(sub)}</small></div>`}
function table(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c??''}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}" class="empty">此範圍沒有正式資料</td></tr>`}</tbody></table></div>`}
function head(title,desc,actions=''){return `<div class="page-head"><div><h1>${esc(title)}</h1><p>${esc(desc)}</p></div><div class="actions">${actions}</div></div>`}
function centerSelect(){return `<label>外送中心<select id="centerFilter"><option value="">全市場</option>${state.centers.map(c=>`<option value="${esc(c.id)}" ${state.center===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label>`}
function groupSelect(){return `<label>Group<select id="groupFilter"><option value="">全部 Group</option>${groups().map(g=>`<option value="${esc(g)}" ${state.group===g?'selected':''}>${esc(g)}</option>`).join('')}</select></label>`}
function filterBar(extra=''){return `<div class="filters">${centerSelect()}${groupSelect()}<label>週起始日<input id="weekFilter" type="date" value="${state.weekStart}"></label>${extra}<button class="ghost" id="reload">重新同步</button></div>`}
function bindFilters(){const c=$('centerFilter'),g=$('groupFilter'),w=$('weekFilter');if(c){if(state.profile?.role!=='op_admin'&&state.profile?.role!=='admin')c.disabled=true;c.onchange=()=>{state.center=c.value;state.group='';render()}}if(g)g.onchange=()=>{state.group=g.value;render()};if(w)w.onchange=async()=>{state.weekStart=weekMonday(new Date(w.value+'T12:00:00'));await loadWeek();render()};if($('reload'))$('reload').onclick=async()=>{await loadCore();render();notify('已重新同步正式資料')}}
function exportCsv(filename,headers,rows){const csv='\ufeff'+[headers,...rows].map(row=>row.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=filename+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),3000)}
function exportExcel(filename,headers,rows){if(!window.KFCXLSX)throw Error('Excel 匯出元件未載入');window.KFCXLSX.download(filename,[{name:'明細',headers,rows}])}
function exportWorkbook(filename,sheets){if(!window.KFCXLSX)throw Error('Excel 匯出元件未載入');window.KFCXLSX.download(filename,sheets)}
function rosterExport(){
 const day=state.day,g=state.group||'',records=state.rosters.filter(r=>r.work_date===day&&(!state.center||r.center_id===state.center)&&(!g||r.group_code===g));
 const entries=g?[{group:g,rows:state.localDraft[key(day,g)]||getRoster(day,g)}]:records.map(r=>({group:r.group_code,rows:state.localDraft[key(day,r.group_code)]||rowsOf(r)}));
 const seen=new Set(),people=[];
 for(const entry of entries)for(const raw of entry.rows){const r=normalizeRow(raw);const employee=r.employee_id||r.employee_name;if(!employee)continue;const rowKey=String(employee)+'|'+entry.group;if(seen.has(rowKey))continue;seen.add(rowKey);people.push([r.employee_name||state.employees.find(e=>e.id===r.employee_id)?.employee_name||'',state.center,entry.group,...slots.map((_,i)=>({delivery:'外送',duty:'值班',break:'休息',meeting:'會議',training:'訓練',admin:'行政'}[slotValue(r,i)]||'')),rowHours(r)])}
 const ds=filterDms().filter(x=>x.business_date===day), tc=slots.map(t=>ds.filter(x=>String(x.bucket_time||'').slice(0,5)===t).reduce((n,x)=>n+Number(x.own_tc||0),0));
 const periods=slots.map((t,i)=>{const seenDelivery=new Set(),seenDuty=new Set();for(const entry of entries)for(const raw of entry.rows){const r=normalizeRow(raw),id=r.employee_id||r.employee_name;if(slotValue(r,i)==='delivery')seenDelivery.add(id);if(slotValue(r,i)==='duty')seenDuty.add(id)}const need=Math.ceil(tc[i]/Math.max(.5,state.tplh*.5));return [t,tc[i],need,seenDelivery.size,seenDuty.size,seenDelivery.size-need]});
 exportWorkbook('KFC_階梯排班_'+(state.center||'全市場')+'_'+(g||'全中心')+'_'+day,[{name:'階梯班表',headers:['員工','中心','Group',...slots,'工作工時'],rows:people},{name:'30分鐘運能',headers:['時段','OWN TC','需求外送人數','已排外送人數','已排值班人數','人力差異'],rows:periods}])
}

function hoursExport(){if(state.monthLoaded!==state.month)return notify('請先載入完整月份資料',true);const employees=filteredEmployees().filter(e=>e.active);const rows=employees.map(e=>{const h=uniqueHours(monthRows().filter(r=>r.employee_id===e.id));return [e.employee_code,e.employee_name,e.center_id,e.group_code,h,h<28?'低於 28h':h>120?'超過 120h':'正常']});const detail=monthRows().flatMap(r=>slots.map((t,i)=>slotValue(r,i)?[r.work_date,r.employee_name,r.group_code,t,slotValue(r,i)]:null).filter(Boolean));exportWorkbook('KFC_員工工時_'+state.month,[{name:'月工時',headers:['員工編號','姓名','中心','Group','工時','提醒'],rows},{name:'時段明細',headers:['日期','員工','Group','時段','工作類型'],rows:detail}])}
function overviewData(){
 const dms=filterDms(), rows=allRosterRows(), days=Array.from({length:7},(_,i)=>addDays(state.weekStart,i));
 const typed=new Map();
 for(const r of rows)for(let i=0;i<slots.length;i++){
  const type=slotValue(r,i);if(!type||type==='break')continue;
  const id=r.employee_id||r.employee_name;if(!id)continue;
  const k=`${id}|${r.work_date}|${slotTime(i)}`;
  if(!typed.has(k))typed.set(k,{date:r.work_date,time:slotTime(i),type,employee:id});
  else if(typed.get(k).type!==type)typed.get(k).conflict=true;
 }
 const shifts=[...typed.values()], tplh=Math.max(.1,Number(state.tplh)||2);
 const byDay=days.map(date=>{const tc=totalTc(dms.filter(x=>x.business_date===date));const ss=shifts.filter(x=>x.date===date);const delivery=ss.filter(x=>x.type==='delivery').length*.5,duty=ss.filter(x=>x.type==='duty').length*.5,other=ss.filter(x=>!['delivery','duty'].includes(x.type)).length*.5;return {date,tc,need:tc/tplh,delivery,duty,other,scheduled:delivery+duty+other,variance:delivery-tc/tplh,tplh:delivery?tc/delivery:null}});
 const matrix=slots.map(time=>({time,cells:days.map(date=>{const tc=totalTc(dms.filter(x=>x.business_date===date&&String(x.bucket_time||'').slice(0,5)===time));const ss=shifts.filter(x=>x.date===date&&x.time===time);const delivery=ss.filter(x=>x.type==='delivery').length,duty=ss.filter(x=>x.type==='duty').length,need=Math.ceil(tc/(tplh*.5));return {tc,need,delivery,duty,gap:Math.max(0,need-delivery)}})}));
 return {days,byDay,matrix,tc:byDay.reduce((n,d)=>n+d.tc,0),delivery:byDay.reduce((n,d)=>n+d.delivery,0),duty:byDay.reduce((n,d)=>n+d.duty,0),other:byDay.reduce((n,d)=>n+d.other,0),conflicts:shifts.filter(x=>x.conflict).length};
}
function pageOverview(){
 const x=overviewData(),days=x.days,selected=days.includes(state.overviewDay)?state.overviewDay:days[0];state.overviewDay=selected;
 const dayNames=['週一','週二','週三','週四','週五','週六','週日'];
 const dayRows=x.byDay.map((d,i)=>{const planned=d.scheduled,variance=d.delivery-d.need;return `<tr><td class="ov-date"><b>${dayNames[i]}</b><small>${d.date.slice(5).replace('-','/')}</small></td><td>${num(d.tc)}</td><td>${d.tplh===null?'—':num(d.tplh,2)}</td><td>${num(d.need,1)}</td><td>${num(planned,1)}</td><td>${num(d.duty,1)}</td><td>${num(d.delivery,1)}</td><td>${num(d.other,1)}</td><td class="${variance<0?'ov-negative':'ov-positive'}">${variance>0?'+':''}${num(variance,1)}</td></tr>`}).join('');
 const t=x.byDay.reduce((a,d)=>({tc:a.tc+d.tc,need:a.need+d.need,scheduled:a.scheduled+d.scheduled,duty:a.duty+d.duty,delivery:a.delivery+d.delivery,other:a.other+d.other}),{tc:0,need:0,scheduled:0,duty:0,delivery:0,other:0});
 const tvar=t.delivery-t.need,ttplh=t.delivery?t.tc/t.delivery:null;
 const weekly=`<div class="ov-section"><div class="ov-section-head"><h2>整週排班總覽</h2><span>工時計算：小時</span></div><div class="ov-table-wrap"><table class="ov-week-table"><thead><tr>${['日期','預測 OWN TC','預估 TPLH','需求工時','排班工時','值班工時','外送工時','其他工時','工時差異'].map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${dayRows}<tr class="ov-total"><td>整週合計</td><td>${num(t.tc)}</td><td>${ttplh===null?'—':num(ttplh,2)}</td><td>${num(t.need,1)}</td><td>${num(t.scheduled,1)}</td><td>${num(t.duty,1)}</td><td>${num(t.delivery,1)}</td><td>${num(t.other,1)}</td><td class="${tvar<0?'ov-negative':'ov-positive'}">${tvar>0?'+':''}${num(tvar,1)}</td></tr></tbody></table></div></div>`;
 const idx=days.indexOf(selected);const matrix=x.matrix.map(r=>{const c=r.cells[idx],delta=c.delivery-c.need;return `<tr><td>${r.time}</td><td>${num(c.tc)}</td><td>${num(c.need)}</td><td>${num(c.delivery)}</td><td>${num(c.duty)}</td><td class="${delta<0?'ov-negative':'ov-positive'}">${delta>0?'+':''}${num(delta)}</td><td class="${delta<0?'ov-negative':'ov-positive'}">${delta<0?'人力不足':delta>0?'人力過量':'符合需求'}</td></tr>`}).join('');
 return `<div class="ov-shell"><div class="ov-heading"><div><h1>班表總覽</h1><p>KFC 智慧排班｜預測 TC 與 30 分鐘人力需求</p></div><span class="ov-management">管理介面</span></div><div class="ov-filters"><div class="ov-filter-grid">${centerSelect()}${groupSelect()}</div><div class="ov-date-control"><label>選擇起始日期（星期一）</label><div class="ov-week-controls"><input type="date" id="weekFilter" value="${state.weekStart}"><button id="overviewPrev" class="ghost">上一週</button><button id="overviewNext" class="ghost">下一週</button></div></div></div>${weekly}<div class="ov-section ov-lower"><div class="ov-section-head"><div><h2>30 分鐘人力需求與缺口</h2><p>選擇日期，查看當天各時段的人力配置</p></div><button class="ghost" id="overviewExport">⇩ 匯出 Excel</button></div><div class="ov-day-tabs">${days.map((d,i)=>`<button class="ov-day-tab ${selected===d?'selected':''}" data-overview-day="${d}">${'一二三四五六日'[i]} ${d.slice(5).replace('-','/')}</button>`).join('')}</div><div class="ov-table-wrap"><table class="ov-slot-table"><thead><tr>${['時段','預測 OWN TC','需求人數','已排外送人數','值班人數','缺口／過量','狀態'].map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${matrix}</tbody></table></div><p class="ov-footnote">以上為營運預測數字，非正式 TC 或班表資料時會顯示載入失敗。正式班表依所選中心、Group、週次與排班設定計算；跨 Group 同員工同時段不重複計算。</p></div></div>`;
}
function exportOverview(){const x=overviewData();exportWorkbook('KFC_班表總覽_'+state.weekStart+'.xlsx',[
 {name:'週營運總覽',headers:['日期','OWN TC','需求外送工時','已排外送工時','值班工時','其他工時','全部工作工時','外送工時差異','外送 TPLH'],rows:x.byDay.map(d=>[d.date,d.tc,d.need,d.delivery,d.duty,d.other,d.scheduled,d.variance,d.tplh??''])},
 {name:'30分鐘人力缺口',headers:['日期','時段','OWN TC','需求外送員','已排外送員','值班人數','缺口人數'],rows:x.matrix.flatMap(r=>r.cells.map((c,i)=>[x.days[i],r.time,c.tc,c.need,c.delivery,c.duty,c.gap]))}
]);}

// 第2頁：只補入既有階梯表的排序與可排班／指休限制，不改版面架構。
function weekdayOf(date){const d=new Date(date+'T12:00:00').getDay();return d===0?7:d}
function timeInWindow(time,a,b){const t=minuteOf(time),start=minuteOf(a),end=minuteOf(b);return end>start?t>=start&&t<end:(t>=start||t<end)}
function slotRestriction(employeeId,date,time){
 if(!employeeId)return '';
 const exceptions=state.exceptions.filter(x=>x.employee_id===employeeId&&x.work_date===date);
 for(const ex of exceptions){
  const kind=String(ex.exception_type||'').toLowerCase();
  let windows=ex.windows;
  if(typeof windows==='string'){try{windows=JSON.parse(windows)}catch{windows=[]}}
  if(!Array.isArray(windows))windows=windows?.windows||[];
  const covers=windows.length===0||windows.some(w=>timeInWindow(time,w.start_time||w.start||w.from,w.end_time||w.end||w.to));
  if(covers&&['off','day_off','leave','休假','指休','unavailable'].includes(kind))return '指休';
  if(covers&&['available','availability','work'].includes(kind))return '';
 }
 const base=state.regular.filter(x=>x.employee_id===employeeId&&Number(x.weekday)===weekdayOf(date));
 if(base.length&&!base.some(w=>timeInWindow(time,w.start_time,w.end_time)))return '不可上班';
 return '';
}
function sortDutyFirst(rows){return rows.map((r,i)=>({r,i,duty:slots.findIndex((_,j)=>slotValue(r,j)==='duty'),first:slots.findIndex((_,j)=>Boolean(slotValue(r,j)))})).sort((a,b)=>{
 const da=a.duty>=0,db=b.duty>=0;if(da!==db)return da?-1:1;
 if(da&&a.duty!==b.duty)return a.duty-b.duty;
 return (a.first<0?999:a.first)-(b.first<0?999:b.first)||a.i-b.i;
 }).map(x=>x.r)}
function pageStair(){
 const day=state.day, group=state.group||'', canEdit=Boolean(group&&state.center);
 const relevant=state.rosters.filter(r=>r.work_date===day&&(!state.center||r.center_id===state.center)&&(!group||r.group_code===group));
 const allRows=group?currentStairRows().map(normalizeRow):relevant.flatMap(r=>getRoster(day,r.group_code).map(x=>({...normalizeRow(x),_group:r.group_code})));
 const active=filteredEmployees().filter(e=>e.active);
 const seen=new Set(allRows.map(r=>r.employee_id));
 const rows=sortDutyFirst(group?allRows:[...allRows,...active.filter(e=>!seen.has(e.id)).map(e=>({employee_id:e.id,employee_name:e.employee_name,_group:e.group_code,slots:{}}))]);
 const ds=filterDms().filter(x=>x.business_date===day);
 const selectedRestaurants=filteredRestaurants();
 const byRestaurant=selectedRestaurants.map(r=>({r,tc:slots.map(t=>ds.filter(x=>String(x.restaurant_id)===String(r.id)&&String(x.bucket_time||'').slice(0,5)===t).reduce((n,x)=>n+Number(x.own_tc||0),0))}));
 const tc=slots.map((t,i)=>byRestaurant.reduce((n,r)=>n+r.tc[i],0));
 const demand=tc.map(n=>Math.ceil(n/(Math.max(.5,state.tplh)*.5)));
 const assigned=slots.map((t,i)=>new Set(rows.filter(r=>slotValue(r,i)==='delivery').map(r=>r.employee_id||r.employee_name)).size);
 const duty=slots.map((t,i)=>new Set(rows.filter(r=>slotValue(r,i)==='duty').map(r=>r.employee_id||r.employee_name)).size);
 const gap=demand.map((n,i)=>assigned[i]-n);
 const typeNames={delivery:'外送',duty:'值班',break:'休息',meeting:'會議',training:'訓練',admin:'行政'};
 const tcRow=(name,values,cls='')=>`<tr class="stair-summary ${cls}"><td class="fixed">${esc(name)}</td>${values.map((v,i)=>`<td class="${i%2?'half':'hour'}">${v}</td>`).join('')}</tr>`;
 const restaurantRows=group?byRestaurant.map(({r,tc:values})=>tcRow('↳ '+r.restaurant_name,values.map(n=>n||'—'),'restaurant-row')).join(''):'';
 const rowHtml=rows.map((r,j)=>`<tr><td class="fixed stair-employee"><b>${esc(r.employee_name||state.employees.find(e=>e.id===r.employee_id)?.employee_name||'未命名')}</b><small>${esc(r._group||group||'')} · ${num(rowHours(r),1)}h</small></td>${slots.map((t,i)=>{const val=slotValue(r,i),restriction=slotRestriction(r.employee_id,day,t),unassigned=!val&&restriction;return `<td class="${i%2?'half':'hour'}"><button class="slot ${esc(val)} ${unassigned?'slot-restricted':''}" data-row="${j}" data-slot="${i}" ${canEdit?'':'disabled'} title="${esc(r.employee_name)} ${t} ${esc(restriction||typeNames[val]||'未排')}">${val?esc(typeNames[val]?.slice(0,1)||val.slice(0,1)):restriction==='指休'?'休':restriction==='不可上班'?'×':'·'}</button></td>`}).join('')}</tr>`).join('');
 const headers=slots.map((t,i)=>`<th class="${i%2?'half':'hour'}">${t}</th>`).join('');
 return `<div class="stair-shell"><div class="stair-top"><div><h1>階梯排班</h1><p>30 分鐘階梯班表｜值班、外送、休息及其他工作類型</p></div><div class="stair-actions"><button class="ghost" id="rosterExport">↓ 匯出 Excel</button><button class="ghost" id="undoRoster">↶ 復原</button><button class="primary" id="saveRoster" ${canEdit?'':'disabled'}>儲存班表</button></div></div>
 ${filterBar(`<label>排班日期<input id="rosterDay" type="date" value="${day}"></label><label>工作類型<select id="slotType">${[['delivery','外送'],['duty','值班'],['break','休息'],['meeting','會議'],['training','訓練'],['admin','行政'],['','清除']].map(([v,n])=>`<option value="${v}" ${state.slotType===v?'selected':''}>${n}</option>`).join('')}</select></label><button class="ghost" id="addStaff" ${canEdit?'':'disabled'}>＋ 新增員工列</button>`)}
 <div class="stair-mode">${group?`<b>Group ${esc(group)} 編輯模式</b> · 顯示餐廳 OWN TC 與本 Group 員工，點選時段即可排班。`:'<b>全中心檢視模式</b> · 顯示全部員工；選擇 Group 後才可修改及儲存，避免覆蓋其他 Group。'}</div>
 <div class="stair-mini-stats"><div><span>OWN TC</span><b>${num(tc.reduce((a,b)=>a+b,0))}</b></div><div><span>建議外送工時</span><b>${num(tc.reduce((a,b)=>a+b,0)/Math.max(.5,state.tplh),1)} h</b></div><div><span>已排外送工時</span><b>${num(assigned.reduce((a,b)=>a+b,0)*.5,1)} h</b></div><div><span>值班工時</span><b>${num(duty.reduce((a,b)=>a+b,0)*.5,1)} h</b></div><div><span>預估 TPLH</span><b>${assigned.reduce((a,b)=>a+b,0)?num(tc.reduce((a,b)=>a+b,0)/(assigned.reduce((a,b)=>a+b,0)*.5),2):'—'}</b></div></div>
 <div class="stair-legend">${[['delivery','外送'],['duty','值班'],['break','休息'],['meeting','會議'],['training','訓練'],['admin','行政']].map(([c,n])=>`<span class="legend-${c}">${n}</span>`).join('')}<small>每小時深色分隔線｜半小時淺色分隔線</small></div>
 <div class="stair-scroll"><table class="stair-grid"><thead><tr><th class="fixed">員工／餐廳 · 時段</th>${headers}</tr></thead><tbody>${tcRow('預測 OWN TC',tc)}${restaurantRows}${tcRow('需求外送人數',demand)}${tcRow('已排外送人數',assigned)}${tcRow('已排值班人數',duty)}${tcRow('人力差異',gap.map(n=>`<span class="${n<0?'stair-short':'stair-ok'}">${n>0?'+':''}${n}</span>`),'stair-gap')}${rowHtml}</tbody></table></div>
 <p class="stair-foot">營運時段：${esc(state.operatingStart)}～${esc(state.operatingEnd)}（隔日），由系統設定控制。每格 30 分鐘。休息不計入工時。未儲存修改不會寫入 Supabase。</p></div>`;
}

function pageForecast(){const f=state.forecastResult, rows=f?.restaurants||[], periods=f?.periods||[];return head('TC 需求預測','指定日期後按「執行預測」，依前四週相同星期的 DMS OWN TC 估算；未取得資料不顯示假預測。','<button class="ghost" id="forecastExport" '+(!f?'disabled':'')+'>匯出預測 Excel</button>')+filterBar(`<label>預測日期<input id="forecastDate" type="date" value="${state.forecastDate}"></label><label>TC 調整 %<input id="forecastPct" type="number" min="-100" max="300" value="${state.forecastPct}"></label><label>TPLH<input id="tplh" type="number" min="0.5" max="8" step="0.1" value="${state.tplh}"></label><button id="runForecast" class="primary" ${state.forecastBusy?'disabled':''}>${state.forecastBusy?'計算中…':'執行預測'}</button>`)+(!f?'<div class="card"><h3>尚未執行預測</h3><p>請先選擇日期及參數，再按「執行預測」。將查詢前四週同星期歷史 OWN TC，依餐廳與 30 分鐘時段計算平均。歷史資料不足時會顯示警告，不會以零或示範值取代。</p></div>':`<div class="kpis">${kpi('預測日期',f.date,'')}${kpi('歷史可用天數',f.available+'/4','同星期')}${kpi('預測 OWN TC',num(f.tc,1),'依歷史平均與調整比例')}${kpi('需求工時',num(f.tc/state.tplh,1),'TC ÷ TPLH')}</div>${f.available<4?'<div class="hint">注意：歷史樣本不足四週，請謹慎使用。</div>':''}<div class="grid2"><div class="card"><h3>30 分鐘需求</h3>${table(['時段','預測 OWN TC','建議人數'],periods.map(r=>[r.time,num(r.tc,1),num(Math.ceil(r.tc/(state.tplh*.5)))]))}</div><div class="card"><h3>餐廳預測與駐點參考</h3>${table(['中心','Group','餐廳','預測 OWN TC','需求工時'],rows.map(r=>[esc(r.center),esc(r.group),esc(r.name),num(r.tc,1),num(r.tc/state.tplh,1)]))}</div></div><div class="card"><h3>餐廳 × 30 分鐘需求明細</h3><p class="note">依同星期歷史訂單預測，顯示餐廳各時段 OWN TC；目前仍未套入天氣、促銷及特殊節日模型。</p>${table(['中心','Group','餐廳',...slots],rows.map(r=>[esc(r.center),esc(r.group),esc(r.name),...slots.map(t=>num(r.periods?.[t]||0,1))]))}</div><div class="hint">目前為同星期歷史平均基準預測；天氣、節日、促銷及可用 Rider 的自動缺口判斷尚未完成串接，請勿將本結果視為完整預測模型。</div>`)}
async function runForecast(){if(state.forecastBusy)return;state.forecastBusy=true;state.forecastResult=null;render();try{const dates=Array.from({length:4},(_,i)=>addDays(state.forecastDate,-7*(i+1)));const start=dates[3],end=dates[0];const rows=await fetchAll('dms_30m',`select=center_id,restaurant_id,business_date,bucket_time,own_tc&business_date=gte.${start}&business_date=lte.${end}`);if(!Array.isArray(rows))throw Error('歷史資料回傳格式不正確');const filtered=rows.filter(x=>dates.includes(x.business_date));const rs=filteredRestaurants(),ids=new Set(rs.map(r=>String(r.id)));const matched=filtered.filter(x=>ids.has(String(x.restaurant_id))&&(!state.center||x.center_id===state.center));const available=new Set(matched.map(x=>x.business_date)).size;if(!available)throw Error('前四週同星期沒有可用的 OWN TC，無法產生預測');const rate=1+state.forecastPct/100;const sum=(list)=>list.reduce((n,x)=>n+Number(x.own_tc||0),0)*rate/available;const restaurants=rs.map(r=>{const own=matched.filter(x=>String(x.restaurant_id)===String(r.id)),days=new Set(own.map(x=>x.business_date)).size,periods=Object.fromEntries(slots.map(t=>[t,days?own.filter(x=>String(x.bucket_time||'').slice(0,5)===t).reduce((n,x)=>n+Number(x.own_tc||0),0)*rate/days:0]));return {center:r.center_id,group:r.region_code,name:r.restaurant_name,tc:Object.values(periods).reduce((a,b)=>a+b,0),periods}});const periods=slots.map(time=>({time,tc:sum(matched.filter(x=>x.bucket_time?.slice(0,5)===time))}));state.forecastResult={date:state.forecastDate,available,restaurants,periods,tc:sum(matched)};notify(`已完成 ${state.forecastDate} 預測；使用 ${available} 個同星期歷史日期`)}catch(e){notify('預測失敗：'+e.message,true)}finally{state.forecastBusy=false;render()}}

function pageEmployees(){const rows=filteredEmployees().map(e=>[esc(e.employee_code),esc(e.employee_name),esc(e.center_id),esc(e.group_code),esc(state.supports.filter(s=>s.employee_id===e.id).map(s=>s.group_code).join('、')),e.active?'<span class="tag green">啟用</span>':'<span class="tag red">停用</span>',`<button class="ghost" data-edit="${esc(e.id)}">編輯</button> <button class="ghost" data-delete="${esc(e.id)}">刪除</button>`]);return head('員工管理','員工自行建立；主 Group 與支援 Group 分開維護，停用後仍保留歷史班表。','<button id="employeesExport" class="ghost">匯出員工 Excel</button><button id="newEmployee" class="primary">＋ 新增員工</button>')+filterBar()+`<div class="kpis">${kpi('員工總數',filteredEmployees().length,'包含停用')}${kpi('啟用人數',filteredEmployees().filter(e=>e.active).length,'可安排新班表')}${kpi('停用人數',filteredEmployees().filter(e=>!e.active).length,'保留歷史')}${kpi('跨 Group 支援',state.supports.length,'關聯筆數')}${kpi('固定時段',state.regular.length,'已設定筆數')}</div><div class="card"><h3>員工名單</h3>${table(['員工編號','姓名','中心','主 Group','支援 Group','狀態','操作'],rows)}</div><div id="employeeEditor"></div>`}
function employeeForm(e={}){const center=e.center_id||state.center||state.centers[0]?.id||'';return `<div class="card"><h3>${e.id?'編輯員工':'新增員工'}</h3><form id="employeeForm" class="form-grid"><label>員工編號<input id="empCode" required value="${esc(e.employee_code||'')}"></label><label>員工姓名<input id="empName" required value="${esc(e.employee_name||'')}"></label><label>所屬中心<select id="empCenter">${state.centers.map(c=>`<option value="${esc(c.id)}" ${center===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label>主要 Group<select id="empGroup">${groups().map(g=>`<option value="${esc(g)}" ${e.group_code===g?'selected':''}>${esc(g)}</option>`).join('')}</select></label><label>狀態<select id="empActive"><option value="true" ${e.active!==false?'selected':''}>啟用</option><option value="false" ${e.active===false?'selected':''}>停用</option></select></label><label>支援 Group（可複選）<select id="empSupports" multiple size="5">${groups().filter(g=>g!==e.group_code).map(g=>`<option value="${esc(g)}" ${state.supports.some(x=>x.employee_id===e.id&&x.group_code===g)?'selected':''}>${esc(g)}</option>`).join('')}</select></label><label>最低班次工時<input id="empMin" type="number" step="0.5" min="0" value="${esc(e.min_shift_hours??0)}"></label><div class="actions"><button type="submit" class="primary">儲存員工</button><button type="button" id="cancelEmp" class="ghost">取消</button></div></form><p class="note">支援 Group 與固定可排班時段會在員工建立後設定；不刪除有歷史紀錄的員工。</p></div>`}
function pageLeave(){const employees=filteredEmployees(),rows=employees.map(e=>{const base=state.regular.filter(r=>r.employee_id===e.id),exceptions=state.exceptions.filter(r=>r.employee_id===e.id);return [esc(e.employee_name),esc(e.group_code),base.length?`${base.length} 個固定時段`:'未設定（採營運時段）',exceptions.length?`${exceptions.length} 筆`:'尚無異動',`<button class="ghost" data-availability="${esc(e.id)}">設定</button>`]});return head('員工指休','管理每週固定可排班及單週異動。未授權的匿名填寫入口不會開放寫入。','<button id="leaveExport" class="ghost">匯出指休 Excel</button>')+filterBar()+`<div class="card"><h3>可排班與指休狀態</h3>${table(['員工','Group','固定可排班','本週異動','管理'],rows)}</div><div id="leaveEditor"></div><div class="hint">員工獨立填寫連結需額外建立身份驗證及截止日限制，不能只靠公開網址直接寫入 Supabase。</div>`}
function pageHolidays(){const y=Number(state.day.slice(0,4));const years=[y-1,y,y+1];const festivals=['元旦','農曆春節','和平紀念日','兒童節','清明節','勞動節','端午節','中秋節','國慶日','其他國定假日','特殊營運日'];return head('國定假日／特殊日期對照','三年度特殊日期比較；政府行事曆資料需經預覽及確認才可匯入。','<button id="holidayExport" class="ghost">匯出對照 Excel</button>')+filterBar()+`<div class="card"><h3>特殊日期比較</h3>${table(['日期／節日',...years.map(x=>`${x} 年`),'比較原則'],festivals.map(f=>[esc(f),...years.map(()=>'<span class="muted">尚未匯入</span>'),f==='農曆春節'?'同節日同期比較':'同節日／同星期比較']))}</div><div class="hint">不自動設定固定成長率。連假前夕與星期五等特殊對照規則，需搭配實際行事曆及歷史 OWN TC。</div><p class="note">官方資料來源：<a href="https://data.gov.tw/dataset/14718" target="_blank" rel="noopener">政府資料開放平臺—行政機關辦公日曆表</a>。目前尚未完成自動同步，避免顯示未經驗證的假日日期。</p>`}
function pageHours(){const loaded=state.monthLoaded===state.month;const details=filteredEmployees().filter(e=>e.active).map(e=>{const rr=monthRows().filter(r=>r.employee_id===e.id),h=uniqueHours(rr);return {e,h}});const rows=loaded?details.map(({e,h})=>[esc(e.employee_name),esc(e.center_id),esc(e.group_code),num(h,1),h<28?'<span class="tag red">低於 28h</span>':h>120?'<span class="tag red">超過 120h</span>':'<span class="tag green">範圍內</span>']):[];const all=details.map(x=>x.h);return head('人員工時統計','讀取完整月份班表，跨 Group 同一員工同一時段只計一次；零工時啟用員工納入。','<button id="hoursExport" class="ghost">匯出工時 Excel</button>')+filterBar(`<label>統計月份<input id="hoursMonth" type="month" value="${state.month}"></label>`)+(loaded?`<div class="kpis">${kpi('員工數',rows.length,'含零工時')}${kpi('合計工時',num(all.reduce((a,b)=>a+b,0),1),'整月已載入資料')}${kpi('低於 28h',all.filter(x=>x<28).length,'含零工時')}${kpi('超過 120h',all.filter(x=>x>120).length,'高工時提醒',true)}${kpi('平均工時',num(all.reduce((a,b)=>a+b,0)/Math.max(rows.length,1),1),'每位員工')}</div><div class="card"><h3>員工工時明細</h3>${table(['員工','中心','Group','工時','判斷'],rows)}</div>`:'<div class="card"><h3>整月資料尚未成功載入</h3><p>請重新同步，不能將未載入的資料視為零工時。</p></div>')}
function compliance(){
 const issues=[],records=allRosterRows().filter(r=>r.employee_id);
 const employees=new Map();
 for(const r of records){const id=r.employee_id;if(!employees.has(id))employees.set(id,[]);employees.get(id).push(r)}
 const add=(date,name,reason,group)=>issues.push([date,name,reason,group||'']);
 for(const [id,rows] of employees){
  const name=rows[0].employee_name||state.employees.find(e=>e.id===id)?.employee_name||id;
  const byDate=new Map();
  for(const r of rows)for(let i=0;i<slots.length;i++){
   const type=slotValue(r,i);if(!type||type==='break')continue;
   const date=r.work_date, t=slotTime(i), k=date+'|'+t;
   if(!byDate.has(date))byDate.set(date,new Map());
   const dm=byDate.get(date);
   if(!dm.has(t))dm.set(t,[]);
   dm.get(t).push({group:r.group_code,type,idx:i});
  }
  const dates=[...byDate.keys()].sort();let previousEnd=null;
  for(const date of dates){
   const dm=byDate.get(date), ordered=[...dm.entries()].sort((a,b)=>a[0].localeCompare(b[0]));
   if(ordered.length>16)add(date,name,'單日工作超過 8 小時',rows[0].group_code);
   let streak=0,last=-2;
   for(const [time,entries] of ordered){
    const idx=entries[0].idx;
    streak=idx===last+1?streak+1:1;last=idx;
    if(streak===9)add(date,name,'連續工作超過 4 小時',entries[0].group);
    if(new Set(entries.map(x=>x.group)).size>1)add(date,name,'跨 Group 時段重疊',entries[0].group);
   }
   const first=ordered[0][1][0].idx, lastIdx=ordered.at(-1)[1][0].idx;
   const start=Date.parse(date+'T08:00:00')+first*1800000;
   const end=Date.parse(date+'T08:00:00')+(lastIdx+1)*1800000;
   if(previousEnd!==null && (start-previousEnd)/3600000<11)add(date,name,'跨日／跨週休息未達 11 小時',ordered[0][1][0].group);
   previousEnd=end;
  }
 }
 // 值班經理必須依已載入的中心／日期逐時段檢查，避免把未載入資料當作缺人。
 const loadedDates=[...new Set(state.rosters.filter(r=>!state.center||r.center_id===state.center).map(r=>r.work_date))];
 for(const date of loadedDates){
  const centerIds=[...new Set(state.rosters.filter(r=>r.work_date===date&&(!state.center||r.center_id===state.center)).map(r=>r.center_id))];
  for(const center of centerIds){
   const dayRows=records.filter(r=>r.work_date===date&&state.employees.some(e=>e.id===r.employee_id&&e.center_id===center));
   for(let i=0;i<slots.length;i++){
    const hasActivity=dayRows.some(r=>{const t=slotValue(r,i);return t&&t!=='break'});
    if(!hasActivity)continue;
    const hasManager=dayRows.some(r=>['duty','manager','值班'].includes(slotValue(r,i)));
    if(!hasManager)add(date,'中心 '+center,'值班經理缺口 '+slotTime(i),center);
   }
  }
 }
 // 只有有明確全天休假例外紀錄時才判定衝突；其他異動格式不可臆測。
 for(const ex of state.exceptions){
  if(!['off','day_off','leave','休假'].includes(String(ex.exception_type||'').toLowerCase()))continue;
  const rows=records.filter(r=>r.employee_id===ex.employee_id&&r.work_date===ex.work_date);
  if(rows.some(r=>slots.some((_,i)=>{const t=slotValue(r,i);return t&&t!=='break'}))){
   const e=state.employees.find(e=>e.id===ex.employee_id);
   add(ex.work_date,e?.employee_name||ex.employee_id,'已核准休假與排班衝突',rows[0]?.group_code);
  }
 }
 return issues;
}
function pageCompliance(){const issues=compliance();return head('員工休假合規檢查','依已載入班表檢查七類異常；跨週邊界需載入相鄰週資料才能完整驗證。','<button class="ghost" id="complianceExport">匯出檢查 Excel</button><button class="ghost" id="checkAgain">重新檢查</button>')+filterBar()+`<div class="kpis">${kpi('目前發現異常',issues.length,'本週已載入班表')}${kpi('休息間隔','11h','公司排班規則')}${kpi('連續工作','4h','需安排休息')}${kpi('單日上限','8h','管理檢查')}${kpi('檢查類型','7 項','仍需正式資料驗收')}</div><div class="card"><h3>異常明細</h3>${table(['日期','員工','異常類型','Group','修正'],issues.map(i=>[...i.map(esc),`<button class="ghost" data-fix="${esc(i[0])}" data-group="${esc(i[3])}">前往排班</button>`]))}</div><div class="hint">已檢查七類規則；跨週邊界與未載入的休假紀錄無法判斷，不能把「無異常」視為完全合格。</div>`}
function pageSettings(){const sync=Object.entries(state.sync).map(([t,s])=>[esc(t),s==='成功'?'<span class="tag green">讀取成功</span>':`<span class="tag red">${esc(s)}</span>`]);return head('系統設定','中心、餐廳、排班規則及 Supabase 連線狀態。','<button id="settingsExport" class="ghost">匯出組織 Excel</button>')+filterBar()+`<div class="kpis">${kpi('外送中心',state.centers.length,'已啟用')}${kpi('餐廳',state.restaurants.length,'已啟用')}${kpi('Group',groups().length,'動態讀取')}${kpi('員工',state.employees.length,'正式資料')}${kpi('TPLH 目標',num(state.tplh,1),'本次操作設定')}</div><div class="grid2"><div class="card"><h3>基本排班規則</h3><div class="form-grid"><label>OWN TPLH<input id="settingsTplh" type="number" step="0.1" min="0.5" value="${state.tplh}"></label><label>單日工時上限<input value="8 小時" disabled></label><label>跨日休息<input value="11 小時" disabled></label><label>連續工作<input value="4 小時" disabled></label><label>第三方使用率<input value="25%" disabled></label><label>時段間隔<input value="30 分鐘" disabled></label><label>開始時間<input id="settingsStart" type="time" step="1800" value="${state.operatingStart}"></label><label>結束時間（可跨日）<input id="settingsEnd" type="time" step="1800" value="${state.operatingEnd}"></label><button class="ghost" id="saveOperating">套用營運時段</button></div><p class="note">TPLH 目前只作用於此瀏覽器的計算，不會誤寫未建立的設定資料表。</p></div><div class="card"><h3>資料庫 API 讀取結果</h3>${table(['資料表','狀態'],sync)}<p class="note">登入成功不代表全部 API 已完成寫入驗收；此處只列出實際呼叫結果。</p></div></div><div class="card"><h3>餐廳組織對照</h3>${table(['中心','區域／Group','餐廳代碼','餐廳名稱'],state.restaurants.slice(0,100).map(r=>[esc(r.center_id),esc(r.region_code),esc(r.restaurant_code),esc(r.restaurant_name)]))}</div><div class="hint">餐廳新增與 Excel 組織表匯入需建立預覽差異、OP 權限檢查與批次寫入驗證；目前未啟用，避免破壞正式對照資料。</div>`}
function render(){if(!state.profile)return;$('nav').innerHTML=pages.map((p,i)=>`<button data-page="${i}" class="${state.page===i?'active':''}"><span class="num">${i+1}</span>${p}</button>`).join('');$('breadcrumb').textContent=`營運管理 / ${pages[state.page]}`;const views=[pageOverview,pageStair,pageForecast,pageEmployees,pageLeave,pageHolidays,pageHours,pageCompliance,pageSettings];$('content').innerHTML=views[state.page]();document.querySelectorAll('[data-page]').forEach(b=>b.onclick=async()=>{state.page=Number(b.dataset.page);notify('');if(state.page===6&&state.monthLoaded!==state.month)await loadMonth();render()});bindFilters();bindPage()}
function bindPage(){if($('overviewExport'))$('overviewExport').onclick=exportOverview;document.querySelectorAll('[data-overview-day]').forEach(b=>b.onclick=()=>{state.overviewDay=b.dataset.overviewDay;render()});if($('overviewPrev'))$('overviewPrev').onclick=async()=>{state.weekStart=addDays(state.weekStart,-7);await loadWeek();render()};if($('overviewNext'))$('overviewNext').onclick=async()=>{state.weekStart=addDays(state.weekStart,7);await loadWeek();render()};if($('rosterDay'))$('rosterDay').onchange=e=>{state.day=e.target.value;render()};if($('slotType'))$('slotType').onchange=e=>state.slotType=e.target.value;if($('tplh'))$('tplh').onchange=e=>{state.tplh=Number(e.target.value)||2;state.forecastResult=null;render()};if($('forecastPct'))$('forecastPct').onchange=e=>{state.forecastPct=Number(e.target.value)||0;state.forecastResult=null;render()};if($('forecastDate'))$('forecastDate').onchange=e=>{state.forecastDate=e.target.value;state.forecastResult=null;render()};if($('runForecast'))$('runForecast').onclick=runForecast;if($('forecastExport'))$('forecastExport').onclick=()=>{const f=state.forecastResult;if(f)exportWorkbook('KFC_TC預測_'+f.date,[{name:'30分鐘需求',headers:['時段','預測 OWN TC','建議人數'],rows:f.periods.map(r=>[r.time,r.tc,Math.ceil(r.tc/(state.tplh*.5))])},{name:'餐廳預測',headers:['中心','Group','餐廳','預測 OWN TC','需求工時',...slots],rows:f.restaurants.map(r=>[r.center,r.group,r.name,r.tc,r.tc/state.tplh,...slots.map(t=>r.periods?.[t]||0)])}])};if($('holidayExport'))$('holidayExport').onclick=()=>exportExcel('KFC_假日對照_'+state.day.slice(0,4),['節日','去年','今年','明年'],['元旦','農曆春節','和平紀念日','兒童節','清明節','勞動節','端午節','中秋節','國慶日','其他國定假日','特殊營運日'].map(x=>[x,'尚未匯入','尚未匯入','尚未匯入']));if($('settingsExport'))$('settingsExport').onclick=()=>exportExcel('KFC_餐廳組織表',['中心','Group','餐廳代碼','餐廳名稱'],state.restaurants.map(r=>[r.center_id,r.region_code,r.restaurant_code,r.restaurant_name]));if($('saveOperating'))$('saveOperating').onclick=()=>{const a=$('settingsStart').value,b=$('settingsEnd').value;if(!a||!b||a===b||![a,b].every(t=>minuteOf(t)%30===0))return notify('請選擇不同的開始與結束時間，且需以30分鐘為單位',true);state.operatingStart=a;state.operatingEnd=b;localStorage.setItem('kfc_operating_start',a);localStorage.setItem('kfc_operating_end',b);refreshOperatingTimes();render();notify('營運時段已套用至本瀏覽器。尚未寫入 Supabase，其他裝置不會同步。')};if($('settingsTplh'))$('settingsTplh').onchange=e=>{state.tplh=Number(e.target.value)||2;render()};if($('hoursMonth'))$('hoursMonth').onchange=async e=>{state.month=e.target.value;await loadMonth();render()};if($('hoursExport'))$('hoursExport').onclick=()=>hoursExport();if($('checkAgain'))$('checkAgain').onclick=render;if($('complianceExport'))$('complianceExport').onclick=()=>exportExcel('KFC_合規檢查_'+state.weekStart,['日期','員工','異常類型','Group'],compliance());document.querySelectorAll('[data-fix]').forEach(b=>b.onclick=()=>{state.day=b.dataset.fix;state.group=b.dataset.group;state.page=1;render()});bindStair();bindEmployees();bindLeave()}
function currentStairRows(){const g=state.group;if(!g)throw new Error('請先選擇 Group 才能編輯排班');const k=key(state.day,g);if(!state.localDraft[k]){const original=getRoster(state.day,g);state.localDraft[k]=original.length?structuredClone(original).map(normalizeRow):filteredEmployees().filter(e=>e.active&&(e.group_code===g||state.supports.some(s=>s.employee_id===e.id&&s.group_code===g))).map(e=>({employee_id:e.id,employee_name:e.employee_name,slots:{}}))}return state.localDraft[k]}
function bindStair(){if($('rosterExport'))$('rosterExport').onclick=rosterExport;if($('undoRoster'))$('undoRoster').onclick=()=>{const last=state.undoStack.pop();if(!last)return notify('沒有可復原的操作');state.localDraft[last.key]=last.rows;render();notify('已復原上一步（尚未儲存）')};document.querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>{if(!state.group)return notify('請先選擇 Group',true);const rows=currentStairRows(),displayRows=sortDutyFirst(rows.map(normalizeRow)),shown=displayRows[Number(b.dataset.row)],r=rows.find(x=>x.employee_id===shown?.employee_id),i=Number(b.dataset.slot);if(!r)return;const reason=slotRestriction(r.employee_id,state.day,slotTime(i));if(reason&&state.slotType&&state.slotType!=='break')return notify(`${r.employee_name||shown.employee_name} ${slotTime(i)} ${reason}，不可直接排班；請先至員工指休調整。`,true);const k=key(state.day,state.group||groups()[0]||'');state.undoStack.push({key:k,rows:structuredClone(rows)});if(state.undoStack.length>30)state.undoStack.shift();if(!r.slots||Array.isArray(r.slots))r.slots={};if(state.slotType)r.slots[slotTime(i)]=state.slotType;else delete r.slots[slotTime(i)];render()});if($('addStaff'))$('addStaff').onclick=()=>{if(!state.group)return notify('請先選擇 Group',true);const list=filteredEmployees().filter(e=>e.active);const rows=currentStairRows(),remaining=list.filter(e=>!rows.some(r=>r.employee_id===e.id));if(!remaining.length)return notify('沒有可新增的員工');const code=prompt('請輸入員工編號：\n'+remaining.map(e=>`${e.employee_code} ${e.employee_name}`).join('\n'));if(!code)return;const e=remaining.find(e=>e.employee_code===code.trim());if(!e)return notify('找不到員工編號',true);rows.push({employee_id:e.id,employee_name:e.employee_name,slots:{}});render()};if($('saveRoster'))$('saveRoster').onclick=async()=>{if(!state.center)return notify('請先選擇單一中心，才能儲存班表。',true);const g=state.group;if(!g)return notify('請先選擇 Group，避免將班表儲存到錯誤區域',true);if(!confirm(`確定儲存 ${state.center} / ${g} / ${state.day} 的班表？`))return;const rows=currentStairRows();const conflicts=rows.flatMap(r=>slots.filter((t,i)=>{const v=slotValue(normalizeRow(r),i);return v&&v!=='break'&&slotRestriction(r.employee_id,state.day,t)}).map(t=>`${r.employee_name||r.employee_id} ${t}`));if(conflicts.length)return notify('班表與指休／可上班時間衝突，請先修正：'+conflicts.slice(0,5).join('、'),true);try{await rest('scheduler_daily_rosters','on_conflict=center_id,work_date,group_code',{method:'POST',headers:{'Prefer':'resolution=merge-duplicates,return=representation'},body:[{center_id:state.center,work_date:state.day,group_code:g,rows,updated_by:state.profile.user_id}]});notify('已儲存至 Supabase');await loadWeek();render()}catch(e){notify(`儲存失敗：${e.message}`,true)}}}
function bindEmployees(){if($('employeesExport'))$('employeesExport').onclick=()=>exportExcel('KFC_員工清單',['員工編號','姓名','中心','主 Group','支援 Group','狀態'],filteredEmployees().map(e=>[e.employee_code,e.employee_name,e.center_id,e.group_code,state.supports.filter(x=>x.employee_id===e.id).map(x=>x.group_code).join('、'),e.active?'啟用':'停用']));if($('newEmployee'))$('newEmployee').onclick=()=>openEmployee({});document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEmployee(state.employees.find(e=>e.id===b.dataset.edit)||{}));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{const e=state.employees.find(x=>x.id===b.dataset.delete);if(!e)return;const label=`${e.employee_code} ${e.employee_name}`;if(!confirm(`確定檢查是否可刪除「${label}」？\n有歷史班表或指休紀錄者，只允許停用，不會刪除歷史資料。`))return;try{const [a,b,c]=await Promise.all([rest('scheduler_regular_availability',`select=id&employee_id=eq.${e.id}&limit=1`),rest('scheduler_weekly_exceptions',`select=id&employee_id=eq.${e.id}&limit=1`),rest('scheduler_employee_support_groups',`select=employee_id&employee_id=eq.${e.id}&limit=1`)]);const history=await fetchAll('scheduler_daily_rosters',`select=rows&center_id=eq.${encodeURIComponent(e.center_id)}`);const hasRoster=history.some(r=>JSON.stringify(r.rows||[]).includes(e.id));if(hasRoster||b.length||a.length){if(confirm(`「${label}」有歷史班表、指休或固定可排班資料，不能永久刪除。\n是否改為停用員工？`)){await rest('scheduler_employees',`id=eq.${e.id}`,{method:'PATCH',body:{active:false}});await loadCore();render();notify('已停用員工，歷史資料保留')}return}if(!confirm(`未查到此員工的已知歷史紀錄。為避免其他資料表遺失關聯，目前採安全停用，確定？`))return;await rest('scheduler_employees',`id=eq.${e.id}`,{method:'PATCH',body:{active:false}});await loadCore();render();notify('員工已停用；正式永久刪除須確認全部歷史關聯')}catch(err){notify('刪除未完成：'+err.message+'。未確認資料完整性前請勿重試。',true)}})}
function openEmployee(e){$('employeeEditor').innerHTML=employeeForm(e);$('cancelEmp').onclick=()=>{$('employeeEditor').innerHTML=''};if(state.profile?.role!=='op_admin'&&state.profile?.role!=='admin')$('empCenter').disabled=true;$('employeeForm').onsubmit=async ev=>{ev.preventDefault();const body={employee_code:$('empCode').value.trim(),employee_name:$('empName').value.trim(),center_id:$('empCenter').value,group_code:$('empGroup').value,active:$('empActive').value==='true',min_shift_hours:Number($('empMin').value)||0};if(!body.employee_code||!body.employee_name||!body.group_code)return notify('請填寫完整員工資料',true);try{if(e.id)await rest('scheduler_employees',`id=eq.${e.id}`,{method:'PATCH',body,headers:{'Prefer':'return=representation'}});else {const created=await rest('scheduler_employees','',{method:'POST',body,headers:{'Prefer':'return=representation'}});e={...e,id:created?.[0]?.id};}const target=state.employees.find(x=>x.id===e.id);const id=target?.id||e.id;const selected=[...$('empSupports').selectedOptions].map(o=>o.value).filter(g=>g!==body.group_code);if(id){await rest('scheduler_employee_support_groups',`employee_id=eq.${id}`,{method:'DELETE'});if(selected.length)await rest('scheduler_employee_support_groups','',{method:'POST',body:selected.map(group_code=>({employee_id:id,group_code})),headers:{Prefer:'return=representation'}})}await loadCore();render();notify('員工資料已儲存至 Supabase')}catch(err){notify(`員工儲存失敗：${err.message}`,true)}}}
function bindLeave(){if($('leaveExport'))$('leaveExport').onclick=()=>exportExcel('KFC_指休_'+state.weekStart,['員工','日期','類型','時段'],state.exceptions.filter(x=>filteredEmployees().some(e=>e.id===x.employee_id)).map(x=>[state.employees.find(e=>e.id===x.employee_id)?.employee_name,x.work_date,x.exception_type,JSON.stringify(x.windows)]));document.querySelectorAll('[data-availability]').forEach(b=>b.onclick=()=>{const e=state.employees.find(x=>x.id===b.dataset.availability);if(!e)return;const base=state.regular.filter(r=>r.employee_id===e.id);$('leaveEditor').innerHTML=`<div class="card"><h3>${esc(e.employee_name)}｜固定可排班時段</h3><p class="note">每週 1–7：星期一至星期日；每日至多兩個時段。</p>${table(['星期','時段 1','時段 2'],Array.from({length:7},(_,i)=>{const a=base.filter(r=>r.weekday===i+1).sort((x,y)=>x.window_no-y.window_no);return [`星期${'一二三四五六日'[i]}`,...[0,1].map(j=>a[j]?`${esc(a[j].start_time?.slice(0,5))}–${esc(a[j].end_time?.slice(0,5))}`:'—')]}))}<p class="note">編輯固定可排班時段：星期一至日，最多兩段；留空代表沒有設定（預設可排營運時段）。</p><div class="form-grid"><label>星期<select id="availWeekday">${Array.from({length:7},(_,i)=>`<option value="${i+1}">星期${'一二三四五六日'[i]}</option>`).join('')}</select></label><label>第一段開始<input id="availStart1" type="time"></label><label>第一段結束<input id="availEnd1" type="time"></label><label>第二段開始<input id="availStart2" type="time"></label><label>第二段結束<input id="availEnd2" type="time"></label></div><button class="primary" id="saveAvailability" data-employee="${esc(e.id)}">儲存指定星期</button><p class="hint">儲存時僅修改該員工選定星期的時段，若 Supabase 寫入失敗會提示；請勿在資料庫錯誤時反覆點擊。</p></div>`;const daySelect=$('availWeekday');const fill=()=>{const d=Number(daySelect.value),windows=base.filter(x=>x.weekday===d).sort((a,b)=>a.window_no-b.window_no);for(let i=1;i<=2;i++){const w=windows.find(x=>x.window_no===i)||windows[i-1];$('availStart'+i).value=w?.start_time?.slice(0,5)||'';$('availEnd'+i).value=w?.end_time?.slice(0,5)||''}};daySelect.onchange=fill;fill();$('saveAvailability').onclick=async()=>{const weekday=Number(daySelect.value),windows=[];for(let i=1;i<=2;i++){const a=$('availStart'+i).value,b=$('availEnd'+i).value;if(Boolean(a)!==Boolean(b))return notify('開始與結束時間必須同時填寫',true);if(a&&b){if(a>=b)return notify('結束時間必須晚於開始時間',true);windows.push({employee_id:e.id,weekday,window_no:i,start_time:a,end_time:b})}}if(windows.length===2&&windows[0].end_time>windows[1].start_time)return notify('兩段可排班時間不能重疊',true);if(!confirm('確定儲存 '+e.employee_name+' 的星期'+weekday+' 固定可排班時段？'))return;try{const original=base.filter(x=>x.weekday===weekday);for(const w of original){await rest('scheduler_regular_availability',`id=eq.${w.id}`,{method:'DELETE'})}if(windows.length)await rest('scheduler_regular_availability','',{method:'POST',body:windows,headers:{Prefer:'return=representation'}});await loadCore();render();notify('已更新固定可排班時段')}catch(err){notify('寫入失敗：'+err.message+'；請重新載入確認資料狀態',true)}};})}
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginError').textContent='登入中…';try{await login($('email').value,$('password').value)}catch(err){$('loginError').textContent=err.message}};$('logout').onclick=()=>{state.token=null;state.refresh=null;state.profile=null;sessionStorage.removeItem('kfc_session');$('loginOverlay').hidden=false;$('logout').hidden=true;$('status').textContent='尚未連線';$('content').innerHTML=''};$('menu').onclick=()=>$('sidebar').classList.toggle('open');const saved=sessionStorage.getItem('kfc_session');if(saved){try{const s=JSON.parse(saved);state.token=s.token;state.refresh=s.refresh;bootstrap()}catch{sessionStorage.removeItem('kfc_session')}}
})();
