/* Confirmed requirements integration. No mock operational data; no database schema changes. */
(()=>{
const valid=()=>Boolean(dbToken&&state.dbLoaded&&dbCenter);
const guard=(name)=>`<section class="panel"><h2>${name}</h2><div class="note">請先使用 Supabase Auth 登入並同步正式資料。本頁不顯示示範 TC 或示範員工。</div></section>`;
const num=x=>Number.isFinite(Number(x))?Number(x):0;
const allDays=(start,n)=>Array.from({length:n},(_,i)=>plus(start,i));
const roster=(d)=>groups.flatMap(g=>(state.assigned?.[key(g,d)]||[]).map(r=>({...r,group:g,date:d})));
const activeSlots=r=>(r.cells||[]).map((c,i)=>c&&c!=='break'?i:-1).filter(i=>i>=0);
const rosterHours=(r,onlyDelivery=false)=>(r.cells||[]).filter(x=>onlyDelivery?x==='delivery':x&&x!=='break').length*.5;
const employeeKey=e=>e.id;
const employeeSlots=(id,d)=>roster(d).filter(r=>r.employee===id);
const selectDay=()=>datebar({group:true});
const weekDates=()=>allDays(weekStart(state.date),7);
const sums=ds=>{let own=0,delivery=0,other=0;for(const d of ds)for(const r of roster(d)){delivery+=rosterHours(r,true);other+=rosterHours(r)-rosterHours(r,true)}for(const h of (state.historyTC||[])){if(ds.includes(h.date))own+=num(h.own_tc)}return {own,delivery,other}};
const exportTable=(id,filename)=>{const table=document.getElementById(id);if(!table)return;const lines=[...table.rows].map(r=>[...r.cells].map(c=>'"'+c.innerText.replace(/\s+/g,' ').replace(/"/g,'""')+'"').join(','));download(filename,lines.join('\r\n'),'text/csv;charset=utf-8')};
window.schedulerExportTable=exportTable;
const top=(items)=>`<div class="cards">${items.map(([k,v])=>`<div class="card">${k}<b>${v}</b></div>`).join('')}</div>`;
const prevOverview=overview;
overview=function(){if(!valid())return guard('班表總覽');const ds=weekDates(),m=sums(ds),tplh=2;const need=m.own?m.own/tplh:null;const counts=ds.map(d=>{const r=roster(d);return [d,r.length,r.reduce((a,x)=>a+rosterHours(x,true),0),r.reduce((a,x)=>a+rosterHours(x),0)]});return `<section class="panel"><h2>班表總覽｜每週 OWN TC × 外送工時</h2>${datebar({week:true})}<div class="note">OWN TC 僅統計已同步的歷史 DMS 資料；尚未取得未來預測時，不以歷史數字冒充預測。</div>${top([['已載入歷史 OWN TC',m.own.toLocaleString()],['已排外送工時',m.delivery.toFixed(1)+'h'],['其他工作工時',m.other.toFixed(1)+'h'],['歷史 TC／外送工時',m.delivery?(m.own/m.delivery).toFixed(2):'—']])}<div class="toolbar"><button onclick="schedulerLoadWeek()">同步本週班表</button><button onclick="schedulerExportTable('overview-days','班表總覽.csv')">匯出 CSV（Excel 可開啟）</button></div><div class="scroll"><table id="overview-days" class="table"><thead><tr><th>日期</th><th>班次列數</th><th>外送工時</th><th>所有工作工時</th><th>值班人數（去重）</th></tr></thead><tbody>${counts.map(([d,n,h,all])=>`<tr><td>${d}</td><td>${n}</td><td>${h.toFixed(1)}</td><td>${all.toFixed(1)}</td><td>${new Set(roster(d).filter(r=>activeSlots(r).length).map(r=>r.employee)).size}</td></tr>`).join('')}</tbody></table></div><p class="muted">未來週需求人數與缺口以 TC 需求預測頁的正式預測結果為準。</p></section>`};
const oldForecast=forecastPage;
forecastPage=function(){if(!valid())return guard('TC 需求預測');const g=state.group,rs=restaurants[g]||[],days=typeof eightWeeks==='function'?eightWeeks(state.date):[];const val=(r,t)=>typeof prediction==='function'?prediction(state.date,r,t):{value:null,weeks:0};const multiplier=Number(window.schedulerForecastAdj??0),tplh=Number(window.schedulerMealTplh??2);const factor=1+multiplier/100;return `<section class="panel"><h2>TC 需求預測｜餐廳 × 每 30 分鐘</h2>${selectDay()}<div class="toolbar"><label>預測調整 % <input style="width:90px" type="number" id="forecast-adjust" value="${multiplier}" onchange="window.schedulerForecastAdj=Number(this.value);render()"></label><label>分時段 TPLH <input style="width:85px" type="number" min="0.5" step="0.1" id="forecast-tplh" value="${tplh}" onchange="window.schedulerMealTplh=Math.max(.5,Number(this.value)||2);render()"></label><button class="primary" onclick="dbLoadEightWeeks()">同步前 8 週 DMS</button><button onclick="schedulerExportTable('forecast-table','TC需求預測.csv')">匯出 CSV</button></div><div class="note">需求人數＝向上取整（30 分鐘預測 OWN TC ÷（分時段 TPLH × 0.5））；缺少有效樣本時不產生建議人數。歷史有效樣本 ${state.historyWindow?.rows??0} 筆。</div><div class="scroll"><table class="table" id="forecast-table"><thead><tr><th>時段</th>${rs.map(r=>`<th>${esc(r)}</th>`).join('')}<th>Group TC</th><th>建議外送人數</th><th>樣本週數</th></tr></thead><tbody>${times.map(t=>{const data=rs.map(r=>val(r,t)),complete=rs.length>0&&data.every(x=>x.value!==null&&x.value!==undefined);const total=complete?data.reduce((s,x)=>s+num(x.value),0)*factor:null;return `<tr><td>${t}</td>${data.map(x=>`<td>${x.value==null?'—':(num(x.value)*factor).toFixed(1)}</td>`).join('')}<td>${total===null?'資料不足':total.toFixed(1)}</td><td>${total===null?'—':Math.ceil(total/(tplh*.5))}</td><td>${data.map(x=>x.weeks??0).join(' / ')}</td></tr>`}).join('')}</tbody></table></div><p class="muted">此頁顯示外送員駐點需求基礎；不在階梯排班頁重複顯示人力推薦。</p></section>`};
analysisPage=function(){if(!valid())return guard('人員工時統計');const month=state.date.slice(0,7),start=month+'-01',last=new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).getDate(),ds=allDays(start,last);const records=state.employees.map(e=>{const slots=new Set();let delivery=0;for(const d of ds)for(const r of employeeSlots(e.id,d))r.cells?.forEach((c,i)=>{if(c&&c!=='break'){slots.add(d+'|'+i);if(c==='delivery')delivery+=.5}});return {e,h:slots.size*.5,delivery}});return `<section class="panel"><h2>人員工時統計｜${month}</h2>${datebar({group:true})}${top([['啟用員工',records.length],['低於 28 小時',records.filter(x=>x.h<28).length],['超過 120 小時',records.filter(x=>x.h>120).length],['已排總工時',records.reduce((s,x)=>s+x.h,0).toFixed(1)+'h']])}<div class="toolbar"><button onclick="schedulerExportTable('hours-table','員工工時統計.csv')">匯出 CSV</button></div><div class="note">按月計算；同一員工跨 Group 相同時段只計一次，休息不計工時。28／120 小時為營運追蹤門檻，非法律判定。</div><div class="scroll"><table id="hours-table" class="table"><tr><th>員工</th><th>主要 Group</th><th>月工時</th><th>外送工時（未去重原始計數）</th><th>狀態</th></tr>${records.map(x=>`<tr><td>${esc(x.e.name)}</td><td>${esc(x.e.group)}</td><td>${x.h.toFixed(1)}</td><td>${x.delivery.toFixed(1)}</td><td>${x.h<28?'低於 28h':x.h>120?'超過 120h':'正常'}</td></tr>`).join('')}</table></div></section>`};
const toStamp=(d,i)=>new Date(`${d}T00:00:00+08:00`).getTime()+(8*60+i*30)*60000;
function audit(){const start=weekStart(state.date),ds=allDays(plus(start,-7),21),issues=[];const add=(e,d,type,detail)=>issues.push({e,d,type,detail});for(const e of state.employees){let last=null;for(const d of ds){const rr=employeeSlots(e.id,d),cells=new Map(),worked=new Set();for(const r of rr)r.cells?.forEach((c,i)=>{if(c&&c!=='break'){if(cells.has(i))add(e,d,'跨 Group 重疊',`${times[i]}：${cells.get(i)}／${r.group}`);else cells.set(i,r.group);worked.add(i)}});const idx=[...worked].sort((a,b)=>a-b);if(idx.length>16)add(e,d,'每日超過 8 小時',`${idx.length*.5} 小時`);let continuous=0,prev=-2;for(const i of idx){continuous=i===prev+1?continuous+1:1;if(continuous===9)add(e,d,'連續工作超過 4 小時',times[i]);prev=i}if(idx.length){const first=toStamp(d,idx[0]),end=toStamp(d,idx[idx.length-1]+1);if(last!==null&&(first-last)<11*3600000)add(e,d,'班次間隔不足 11 小時',((first-last)/3600000).toFixed(1)+'h');last=end;}const ex=state.exceptions?.[e.id+'|'+weekStart(d)]?.days?.[d];if(ex?.type==='off'&&idx.length)add(e,d,'指休衝突','全天休假仍有班次');}}
for(const d of allDays(start,7)){for(let i=0;i<times.length;i++){const duty=roster(d).some(r=>r.cells?.[i]==='duty');const any=roster(d).some(r=>r.cells?.[i]&&r.cells[i]!=='break');if(any&&!duty)add({id:'',name:'中心'},d,'缺少值班經理',times[i])}}
return issues.filter(x=>x.d>=start&&x.d<=plus(start,6));}
window.schedulerJumpIssue=(d,eid)=>{state.date=d;state.tab='group';state.schedulerScope='group';if(eid){const row=roster(d).find(r=>r.employee===eid);if(row)state.group=row.group}save();render();document.getElementById('app')?.scrollIntoView({behavior:'smooth'})};
const priorRender=render;
render=function(){if(state.tab!=='compliance')return priorRender();document.getElementById('nav').innerHTML=tabs.map(([id,name])=>`<button class="${id===state.tab?'active':''}" onclick="setTab('${id}')">${name}</button>`).join('');if(!valid()){document.getElementById('app').innerHTML=guard('員工休假合規檢查');return}const issues=audit();document.getElementById('app').innerHTML=`<section class="panel"><h2>員工休假合規檢查｜每週批次</h2>${datebar({week:true})}${top([['本週異常',issues.length],['影響員工',new Set(issues.filter(x=>x.e.id).map(x=>x.e.id)).size],['檢查範圍','前後各 1 週'],['檢查規則','7 類']])}<div class="note">檢查每日 8h、連續 4h、班間 11h、值班經理、跨 Group 重疊、跨週班間隔、指休衝突；僅為公司排班規則檢核，不代表法規合規認證。值班經理需以 duty 工作類型標示。</div><div class="toolbar"><button onclick="render()">重新檢查</button><button onclick="schedulerExportTable('audit-table','排班異常.csv')">匯出 CSV</button></div><div class="scroll"><table class="table" id="audit-table"><tr><th>日期</th><th>員工</th><th>異常類型</th><th>內容</th><th>操作</th></tr>${issues.length?issues.map(x=>`<tr><td>${x.d}</td><td>${esc(x.e.name)}</td><td>${esc(x.type)}</td><td>${esc(x.detail)}</td><td><button onclick="schedulerJumpIssue('${x.d}','${x.e.id}')">前往修正</button></td></tr>`).join(''):'<tr><td colspan="5">目前載入的班表未觸發上述檢查；請確認全週及前後週資料已同步。</td></tr>'}</table></div></section>`};
const oldSettings=v73settings;
// Existing Supabase login and settings remain; remove unsafe local reset actions from visible settings.
v73settings=function(){let s=oldSettings();s=s.replace(/<button class="danger" onclick="if\(confirm\('確定清除所有本機測試修改？'\)\).*?<\/button>/g,'');return s+`<section class="panel"><h2>正式資料串接狀態</h2>${top([['中心',esc(dbCenter||'未登入')],['正式員工',valid()?state.employees.length:'—'],['餐廳',valid()?state.dbRestaurants?.length??0:'—'],['DMS 歷史列數',valid()?state.historyTC?.length??0:'—']])}<div class="toolbar"><button onclick="dbLoad()" ${valid()?'':'disabled'}>重新同步 Supabase</button><button onclick="schedulerLoadWeek()" ${valid()?'':'disabled'}>重新同步班表</button></div><p class="muted">連線狀態代表資料是否成功載入，不代表每項 API 已完成線上讀寫驗收。餐廳組織匯入、天氣與假日同步仍需正式介面及後端驗證。</p></section>`};
render();
})();
