/* KFC scheduler incremental fixes: 8-week OWN TC + support Groups + two-window availability */
(function(){
 const originalLoad=dbLoad;
 let loadedDates=new Set();
 const fmt=d=>d.toISOString().slice(0,10);
 function eightWeeks(date){const a=[];for(let n=1;n<=8;n++)a.push(plus(date,-7*n));return a}
 function prediction(date,restaurant,time){const wanted=eightWeeks(date);const rows=state.historyTC||[];let sum=0,n=0;for(const d of wanted){const r=rows.find(x=>x.date===d&&x.restaurant===restaurant&&x.time===time);if(r&&Number.isFinite(Number(r.own_tc))){sum+=Number(r.own_tc);n++}}return {value:n?Math.round(sum/n):null,weeks:n}}
 window.schedulerPredict=prediction;
 // No zero substitution: a missing restaurant-slot has unknown TC.
 v83HistoricalTC=function(g,i,d=state.date,restaurant=''){if(!restaurant)return null;return prediction(d,restaurant,times[i]).value};
 tc=function(g,i){const k=key(g,state.date)+'|'+i;if(state.forecast[k]!==undefined)return Number(state.forecast[k])||0;const names=restaurants[g]||[];if(!names.length)return null;const vals=names.map(r=>prediction(state.date,r,times[i]).value);return vals.some(x=>x===null)?null:vals.reduce((a,b)=>a+b,0)};
 const originalSetDate=setDate;
 setDate=function(d){if(d!==state.date){state.historyTC=[];state.historyWindow=null;}originalSetDate(d)};
 async function fetchAll(path){let out=[];for(let offset=0;offset<100000;offset+=1000){let sep=path.includes('?')?'&':'?';let page=await dbRequest('/rest/v1/rpc/scheduler_center_dms_by_center',{method:'POST',body:JSON.stringify({...window.schedulerDmsRange,p_center:dbCenter,p_offset:offset,p_limit:1000})});out.push(...page);if(page.length<1000)return out}throw Error('歷史資料超過查詢上限，請縮小查詢範圍')}
 window.dbLoadEightWeeks=async function(){if(!dbToken||!dbCenter)return;const date=state.date;const days=eightWeeks(date);const min=days[7],max=days[0];try{window.schedulerDmsRange={p_from:min,p_to:max};const raw=await fetchAll('scheduler_center_dms');const rest=state.dbRestaurants||[];const map=new Map(rest.map(r=>[String(r.id),r]));const allowed=new Set(days);const result=raw.filter(r=>allowed.has(r.business_date)&&map.has(String(r.restaurant_id))).map(r=>{const info=map.get(String(r.restaurant_id));return {date:r.business_date,group:info.region_code,restaurant:info.restaurant_name,time:r.bucket_time.slice(0,5),own_tc:Number(r.own_tc),activity:'',baseline:0}});state.historyTC=result;state.historyWindow={start:min,end:max,rows:result.length};loadedDates.add(date);render();dbMessage('8 週 OWN TC 已讀取：'+result.length+' 筆，歷史期間 '+min+' 至 '+max)}catch(e){dbMessage('8 週 TC 讀取失敗：'+e.message);state.dbLoaded=false;throw e}};
 dbLoad=async function(){await originalLoad();};
 forecastPage=function(){const ds=eightWeeks(state.date),g=state.group,rs=restaurants[g]||[];return `<section class="panel"><h2>TC 需求預測｜前 8 週相同星期、相同時段 OWN TC</h2>${datebar({group:true})}<div class="toolbar"><button class="primary" onclick="dbLoadEightWeeks()">重新讀取 Supabase 前 8 週</button><span class="tag">${esc(state.historyWindow?.rows??0)} 筆歷史資料</span><span class="muted">缺資料排除、實際 0 單納入平均；每家餐廳分別計算後加總</span></div><div class="note">${!dbToken?'尚未登入 Supabase，無法取得正式預測。請至系統設定登入。':`歷史參考日期：${ds.join('、')}。有效週數少於 8 週會顯示樣本數；無歷史資料顯示「資料不足」。`}</div><div class="scroll"><table class="table"><thead><tr><th>時段</th>${rs.map(r=>`<th>${esc(r)}</th>`).join('')}<th>Group OWN TC</th><th>有效週數</th></tr></thead><tbody>${times.map((t,i)=>{const ps=rs.map(r=>prediction(state.date,r,t));const complete=ps.every(x=>x.value!==null);return `<tr><td>${t}</td>${ps.map(x=>`<td>${x.value===null?'資料不足':x.value} <small class="muted">(${x.weeks}/8)</small></td>`).join('')}<td><b>${complete?ps.reduce((s,x)=>s+x.value,0):'資料不足'}</b></td><td>${ps.map(x=>x.weeks).join(' / ')}</td></tr>`}).join('')}</tbody></table></div></section>`};
 function dayOptions(v){return v77TimeOptions(v)}
 function regularEdit(id,day,action,val){const e=getEmployee(id);if(!e)return;const all=state.regularWeekly??={};let x=all[id];if(!x)x=all[id]=Array.from({length:7},(_,i)=>v77Regular(e,i));let current=x[day]?JSON.parse(JSON.stringify(x[day])):null;
 if(action==='off')current=val?null:[['10:30','15:00']];
 if(action==='add'){current??=[];if(current.length<2)current.push(['17:00','21:00'])}
 if(action==='remove'){current?.splice(Number(val),1);if(!current?.length)current=null}
 if(action.startsWith('time:')){let [,idx,part]=action.split(':');if(current?.[idx])current[idx][Number(part)]=val}
 if(current){const sorted=[...current].sort((a,b)=>a[0].localeCompare(b[0]));if(sorted.some(w=>w[0]>=w[1])||sorted.some((w,i)=>i&&sorted[i-1][1]>w[0]))return alert('可排班時間必須先於結束時間，兩段不可重疊')}
 x[day]=current;save();render();if(dbToken&&e.dbId)saveRegularFull(e,day,current)}
 window.regularEdit=regularEdit;
 async function saveRegularFull(e,day,windows){try{const url='/rest/v1/scheduler_regular_availability?employee_id=eq.'+e.dbId+'&weekday=eq.'+(day+1);await dbRequest(url,{method:'DELETE'});if(windows?.length)await dbRequest('/rest/v1/scheduler_regular_availability',{method:'POST',body:JSON.stringify(windows.map((w,i)=>({employee_id:e.dbId,weekday:day+1,window_no:i+1,start_time:w[0],end_time:w[1]})))});dbMessage('已同步 '+e.name+' 的星期'+(day+1)+'固定時段')}catch(err){dbMessage('固定時段儲存失敗：'+err.message+'；請重新同步核對')}}
 window.updateSupport=async function(id,field,value){const e=getEmployee(id);if(!e)return;const next=field==='primary'?{group:value,support:(e.support||[]).filter(x=>x!==value)}:{support:value?Array.from(new Set([...(e.support||[]),value])).filter(x=>x!==e.group):(e.support||[]).filter(x=>x!==value.slice(1))};if(field==='supportRemove')next.support=(e.support||[]).filter(x=>x!==value);Object.assign(e,next);save();render();if(dbToken&&e.dbId){try{await dbRequest('/rest/v1/scheduler_employees?id=eq.'+e.dbId,{method:'PATCH',body:JSON.stringify({group_code:e.group})});if(field!=='primary'){await dbRequest('/rest/v1/scheduler_employee_support_groups?employee_id=eq.'+e.dbId,{method:'DELETE'});if(e.support.length)await dbRequest('/rest/v1/scheduler_employee_support_groups',{method:'POST',body:JSON.stringify(e.support.map(g=>({employee_id:e.dbId,group_code:g})))})}}catch(err){dbMessage('Group 設定同步失敗：'+err.message)}}};
 v77RegularTable=function(){return `<section class="panel"><h2>員工固定可排班｜星期一至星期日</h2><div class="note">主 Group 與支援 Group 分開設定。每日可設 1～2 段可排班時間；指休只覆蓋指定日期。</div><div class="toolbar"><button class="primary" onclick="v77Export('regular')">匯出固定可排班 Excel（.xlsx）</button><button onclick="setTab('availability')">前往員工指休</button></div><div class="scroll"><table class="table v77-table"><thead><tr><th>員工／主 Group／支援 Group</th>${v77Days.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${state.employees.map(e=>`<tr><th style="min-width:185px">${esc(e.name)}<br><small>主 Group</small><select onchange="updateSupport('${e.id}','primary',this.value)">${groups.map(g=>`<option value="${esc(g)}" ${g===e.group?'selected':''}>${esc(g)}</option>`).join('')}</select><div class="mini">支援：${groups.filter(g=>g!==e.group).map(g=>`<label style="display:block"><input type="checkbox" ${(e.support||[]).includes(g)?'checked':''} onchange="updateSupport('${e.id}',this.checked?'support':'supportRemove','${esc(g)}')"> ${esc(g)}</label>`).join('')}</div></th>${v77Days.map((_,i)=>{const v=v77Regular(e,i);return `<td><label class="v77-off"><input type="checkbox" ${!v?'checked':''} onchange="regularEdit('${e.id}',${i},'off',this.checked)">不可排</label>${(v||[]).map((w,j)=>`<div class="v77-time"><small>${j+1}段</small><select onchange="regularEdit('${e.id}',${i},'time:${j}:0',this.value)">${dayOptions(w[0])}</select>至<select onchange="regularEdit('${e.id}',${i},'time:${j}:1',this.value)">${dayOptions(w[1])}</select>${j===1?`<button onclick="regularEdit('${e.id}',${i},'remove',1)">×</button>`:''}</div>`).join('')}${v&&v.length<2?`<button onclick="regularEdit('${e.id}',${i},'add')">＋ 第二段</button>`:''}</td>`}).join('')}</tr>`).join('')}</tbody></table></div></section>`};
 // Replace legacy employee single-window table with the desired regular weekly table.
 employeesPage=function(){return `<section class="panel"><h2>員工管理｜主 Group 與支援 Group</h2><p class="muted">固定可排班時段在下方直接維護；新增員工請先至系統設定登入資料庫。</p><div class="toolbar"><input id="new-employee-code" placeholder="員工編號"><input id="new-employee-name" placeholder="員工姓名"><select id="new-employee-group">${groups.map(g=>`<option>${esc(g)}</option>`).join('')}</select><button onclick="dbAddEmployee()">＋ 新增員工</button></div></section>`+v77RegularTable()};
 // Supervisor weekly overview uses effective availability, including both windows.
 const oldAvailability=availabilityPage;
 availabilityPage=function(){const start=weekStart(state.date),ds=Array.from({length:7},(_,i)=>plus(start,i));return `<section class="panel"><h2>員工指休｜每週可排班時間總表</h2>${datebar({week:true})}<div class="toolbar"><button class="primary" onclick="v77Export('exceptions')">匯出本週 Excel（.xlsx）</button></div><div class="scroll"><table class="table"><thead><tr><th>員工</th><th>Group</th>${ds.map((d,i)=>`<th>${v77Days[i]} ${d}</th>`).join('')}</tr></thead><tbody>${state.employees.map(e=>`<tr><th>${esc(e.name)}</th><td>${esc(e.group)}</td>${ds.map(d=>{const ws=avAvailability(e,d);return `<td>${!ws?'休':(typeof ws[0]==='string'?[ws]:ws).map(w=>esc(w.join('–'))).join('<br>')}</td>`}).join('')}</tr>`).join('')}</tbody></table></div><p class="muted">同一天兩段班分兩行顯示，空檔不列入可排班時段。</p></section>`+oldAvailability()};
 // Export all effective windows, not only overrides.
 const oldExport=v77Export;
 v77Export=function(type){if(type!=='exceptions')return oldExport(type);const w=weekStart(state.date),ds=Array.from({length:7},(_,i)=>plus(w,i));const rows=[['員工編號','員工姓名','Group',...ds.map((d,i)=>v77Days[i]+' '+d)]];for(const e of state.employees)rows.push([e.id,e.name,e.group,...ds.map(d=>{const ws=avAvailability(e,d);return !ws?'不可排班':(typeof ws[0]==='string'?[ws]:ws).map(a=>a.join('–')).join('\n')})]);const entries=[['[Content_Types].xml','<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>'],['_rels/.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'],['xl/workbook.xml','<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="員工指休" sheetId="1" r:id="rId1"/></sheets></workbook>'],['xl/_rels/workbook.xml.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>'],['xl/worksheets/sheet1.xml',v77Sheet(rows)]];const url=URL.createObjectURL(v77Zip(entries)),a=document.createElement('a');a.href=url;a.download='員工指休_'+w+'.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)};
 // Existing forecast display depends on real historical data, never fabricated demo values.
 render();
})();
